---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: priv-esc-role
rules:
  - apiGroups: [sro.role.ci]
    resources: [testresources]
    verbs: [get]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: priv-esc-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: priv-esc-role
subjects:
  - kind: ServiceAccount
    name: {{ .Values.serviceAccount.name }}
    namespace: {{ .Values.serviceAccount.namespace }}
