---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: priv-esc-clusterrole
rules:
  - apiGroups: [sro.clusterrole.ci]
    resources: [testresources]
    verbs: [get]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: priv-esc-clusterrolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: priv-esc-clusterrole
subjects:
  - kind: ServiceAccount
    name: {{ .Values.serviceAccount.name }}
    namespace: {{ .Values.serviceAccount.namespace }}
